const monsters = {
    "great izuchi":"Type- bird wyvern | Weaknesses- Poison:3,Stun:2,Paralysis:3,Sleep:3,Blast:2,Exhaust:3,Fireblight:1,Waterblight:1,Thunderblight:2,Iceblight:1",
    "great baggi":"Type- bird wyvern | Weaknesses- Poison:1,Stun:1,Paralysis:3,Sleep:0,Blast:3,Exhaust:3,Fireblight:2,Waterblight:1,Thunderblight:1,Iceblight:1",
    "kulu-ya-ku":"Type- bird wyvern | Weaknesses- Poison:1,Stun:2,Paralysis:1,Sleep:1,Blast:2,Exhaust:1,Fireblight:1,Waterblight:2,Thunderblight:1,Iceblight:1",
    "great wroggi": "Type- bird wyvern | Weaknesses- Poison:0,Stun:1,Paralysis:3,Sleep:3,Blast:2,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:1,Iceblight:2",
    "arzuros": "Type- fanged beast | Weaknesses- Poison:3,Stun:2,Paralysis:3,Sleep:3,Blast:2,Exhaust:3,Fireblight:2,Waterblight:1,Thunderblight:1,Iceblight:1",
    "lagombi": "Type- fanged beast | Weaknesses- Poison:3,Stun:2,Paralysis:3,Sleep:1,Blast:3,Exhaust:1,Fireblight:2,Waterblight:1,Thunderblight:1,Iceblight:1",
    "volvidon": "Type- fanged beast | Weaknesses- Poison:1,Stun:2,Paralysis:1,Sleep:1,Blast:2,Exhaust:1,Fireblight:1,Waterblight:2,Thunderblight:1,Iceblight:1",
    "aknosom": "Type- bird wyvern | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:1,Blast:2,Exhaust:1,Fireblight:1,Waterblight:2,Thunderblight:1,Iceblight:1",
    "royal ludroth": "Type- leviathan | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:1,Blast:2,Exhaust:1,Fireblight:2,Waterblight:1,Thunderblight:1,Iceblight:1",
    "barroth": "Type- brute wyvern | Weaknesses- Poison:3,Stun:0,Paralysis:3,Sleep:1,Blast:3,Exhaust:1,Fireblight:2,Waterblight:1,Thunderblight:1,Iceblight:1",
    "khezu": "Type- flying wyvern | Weaknesses- Poison:3,Stun:1,Paralysis:0,Sleep:1,Blast:2,Exhaust:0,Fireblight:2,Waterblight:1,Thunderblight:1,Iceblight:1",
    "tetranadon": "Type- amphibian | Weaknesses- Poison:1,Stun:1,Paralysis:3,Sleep:1,Blast:2,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:2,Iceblight:1",
    "bishaten": "Type- fanged beast | Weaknesses- Poison:0,Stun:1,Paralysis:1,Sleep:1,Blast:2,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:1,Iceblight:2",
    "pukei-pukei": "Type- bird wyvern | Weaknesses- Poison:0,Stun:1,Paralysis:3,Sleep:3,Blast:2,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:2,Iceblight:1",
    "jyuratodus": "Type- piscine wyvern | Weaknesses- Poison:1,Stun:2,Paralysis:1,Sleep:0,Blast:0,Exhaust:3,Fireblight:1,Waterblight:1,Thunderblight:2,Iceblight:1",
    "basarios": "Type- brute wyvern | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:3,Blast:2,Exhaust:1,Fireblight:1,Waterblight:2,Thunderblight:1,Iceblight:1",
    "Somnacanth": "Type- Leviathan | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:0,Blast:2,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:2,Iceblight:1",
    "Rathian": "Type- Flying Wyvern | Weaknesses- Poison:0,Stun:1,Paralysis:1,Sleep:1,Blast:0,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:2,Iceblight:1",
    "Barioth": "Type- Flying Wyvern | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:1,Blast:2,Exhaust:1,Fireblight:2,Waterblight:1,Thunderblight:1,Iceblight:1",
    "Tobi-Kadachi": "Type- Fanged Wyvern | Weaknesses- Poison:3,Stun:1,Paralysis:1,Sleep:1,Blast:2,Exhaust:1,Fireblight:1,Waterblight:2,Thunderblight:1,Iceblight:1",
    "Magnamalo": "Type- Fanged Wyvern | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:1,Blast:0,Exhaust:1,Fireblight:1,Waterblight:2,Thunderblight:1,Iceblight:1",
    "Anjanath": "Type- Brute Wyvern | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:1,Blast:0,Exhaust:1,Fireblight:1,Waterblight:2,Thunderblight:1,Iceblight:1",
    "Nargacuga": "Type- Flying Wyvern | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:1,Blast:2,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:2,Iceblight:1",
    "Mizutsune": "Type- Leviathan | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:1,Blast:2,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:2,Iceblight:1",
    "Goss Harag": "Type- Fanged Beast | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:1,Blast:2,Exhaust:0,Fireblight:2,Waterblight:1,Thunderblight:1,Iceblight:1",
    "Rathalos": "Type- Flying Wyvern | Weaknesses- Poison:0,Stun:1,Paralysis:1,Sleep:1,Blast:0,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:2,Iceblight:1",
    "Almudron": "Type- Leviathan | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:1,Blast:0,Exhaust:1,Fireblight:2,Waterblight:1,Thunderblight:1,Iceblight:1",
    "Zinogre": "Type- Fanged Wyvern | Weaknesses- Poison:1,Stun:1,Paralysis:0,Sleep:1,Blast:2,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:1,Iceblight:2",
    "Tigrex": "Type- Flying Wyvern | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:1,Blast:2,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:2,Iceblight:1",
    "Diablos": "Type- Flying Wyvern | Weaknesses- Poison:1,Stun:0,Paralysis:3,Sleep:1,Blast:2,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:1,Iceblight:2",
    "Rakna-Kadaki": "Type- Temnoceran | Weaknesses- Poison:0,Stun:1,Paralysis:1,Sleep:1,Blast:0,Exhaust:1,Fireblight:1,Waterblight:1,Thunderblight:1,Iceblight:2",
    "Rajang": "Type- Fanged Beast | Weaknesses- Poison:0,Stun:0,Paralysis:0,Sleep:0,Blast:2,Exhaust:0,Fireblight:1,Waterblight:1,Thunderblight:1,Iceblight:2",
    "Bazelgeuse": "Type- Flying Wyvern | Weaknesses- Not known yet",
    "Wind Serpent Ibushi": "Type- Elder Dragon | Weaknesses- Poison:1,Stun:1,Paralysis:1,Sleep:1,Blast:2,Exhaust:0,Fireblight:2,Waterblight:1,Thunderblight:1,Iceblight:1",
    "Thunder Serpent Narwa": "Type- Elder Dragon | Weaknesses- Poison:0,Stun:0,Paralysis:0,Sleep:0,Blast:2,Exhaust:0,Fireblight:1,Waterblight:1,Thunderblight:0,Iceblight:2",
    "Crimson Glow Valstrax": "Type- Elder Dragon | Weaknesses- Not known yet",
    "Daimyo Hermitaur": "Type- Carapaceon | Weaknesses- Poison:3,Stun:1,Paralysis:1,Sleep:1,Blast:2,Exhaust:1,Fireblight:2,Waterblight:1,Thunderblight:2,Iceblight:1"
}