const parts = {    
    "aknosom scale":          "Aknosom (L)",
    "aknosom scale+":        "Aknosom (H)",
    "aknosom feather":        "Aknosom (L)",
    "aknosom feather+":      "Aknosom (H)",
    "aknosom beak":           "Aknosom (L/H)",
    "aknosom crest":          "Aknosom (L)",
    "aknosom crest+":        "Aknosom (H)",
    "arzuros shell":          "Arzuros (L)",
    "arzuros carapace":       "Arzuros (H)",
    "arzuros pelt":           "Arzuros (L)",
    "arzuros pelt+":         "Arzuros (H)",
    "arzuros brace":          "Arzuros (L)",
    "arzuros brace+":        "Arzuros (H)",
    "aqua sac":               "Royal Ludroth (L)",
    "barroth shell":          "Barroth (L)",
    "barroth carapace":       "Barroth (H)",
    "barroth ridge":          "Barroth (L)",
    "barroth ridge+":        "Barroth (H)",
    "barroth claw":           "Barroth (L)",
    "barrother claw+":       "Barroth (H)",
    "barroth scalp":          "Barroth (L/H)",
    "barroth tail":           "Barroth (L/H)",
    "beast gem":              "All High Rank or Master Rank Fanged Beasts",
    "beast tear":             "Arzuros (L/H),Lagombi (L/H),Volvidon (L/H)",
    "bird wyvern gem":        "All High Rank or Master Rank Bird Wyverns",
    "coma sac":               "Great Baggi (H)",
    "crab pearl+":           "Daimyo Hermitaur (M)",
    "dash extract":           "Royal Ludroth (L/H)",
    "electro sac":            "Khezu (L)",
    "fertile mud":            "Barroth (L)",
    "fine black pearl":       "Daimyo Hermitaur (M)",
    "flabby hide":            "Khezu (L)",
    "flame sac":              "Aknosom (L)",
    "great baggi hide":       "Great Baggi (L)",
    "great baggi hide+":     "Great Baggi (H)",
    "great baggi claw":      "Great Baggi (L)",
    "great baggi claw+":      "Great Baggi (H)",
    "great izuchi hide":     "Great Izuchi (L)",
    "great izuchi hide+":     "Great Izuchi (H)",
    "great izuchi pelt":     "Great Izuchi (L)",
    "great izuchi pelt+":     "Great Izuchi (H)",
    "great izuchi tail":     "Great Izuchi (L)",
    "great izuchi tail+":     "Great Izuchi (H)",
    "great wroggi hide":     "Great Wroggi (L)",
    "great wroggi hide+":     "Great Wroggi (H)",
    "great wroggi brace":    "Great Wroggi (L)",
    "great wroggi brace+":    "Great Wroggi (H)",
    "hermitaur cortex":      "Daimyo Hermitaur (M)",
    "hermitaur hardclaw":    "Daimyo Hermitaur (M)",
    "inferno sac":           "Aknosom (H)",
    "jumbo bone":            "Arzuros (L),Lagombi (L),Volvidon (L)",
    "kings beak":            "Great Wroggi (L/H)",
    "kings crest":           "Great Baggi (L/H)",
    "kulu-ya-ku scale":      "Kulu-Ya-Ku (L)",
    "kulu-ya-ku scale+":      "Kulu-Ya-Ku (H)",
    "kulu-ya-ku hide":       "Kulu-Ya-Ku (L)",
    "kulu-ya-ku hide+":       "Kulu-Ya-Ku (H)",
    "kulu-ya-ku plume":      "Kulu-Ya-Ku (L)",
    "kulu-ya-ku plume+":      "Kulu-Ya-Ku (H)",
    "kulu-ya-ku beak":       "Kulu-Ya-Ku (L)",
    "kulu-ya-ku beak+":       "Kulu-Ya-Ku (H)",
    "lagombi pelt":          "Lagombi (L)",
    "lagombi pelt+":          "Lagombi (H)",
    "lagombi plastron":      "Lagombi (L)",
    "lagombi plastron+":      "Lagombi (H)",
    "lagombi iceclaw":       "Lagombi (L)",
    "lagombi frozenclaw":    "Lagombi (L)",
    "lagombi ear":           "Lagombi (L)",
    "lagombi ear+":           "Lagombi (H)",
    "large beast tear":      "All High Rank or Master Rank Fanged Beasts",
    "large wyvern tear":     "All High Rank or Master Rank Wyverns/Leviathans",
    "monster bone m":        "Great Baggi (L),Kulu-Ya-Ku (L),Great Wroggi (L),Aknosom (L),Barroth (L),Khezu (L)",
    "monster bone s":        "Great Izuchi (L)",
    "monster bone+":          "Great Izuchi (H),Great Baggi (H),Kulu-Ya-Ku (H),Great Wroggi (H)",
    "monster broth":         "Volvidon (H)",
    "monster fluid":         "Volvidon (L)",
    "monster hardbone":      "Daimyo Hermitaur (M)",
    "monster keenbone":      "Aknosom (H),Barroth (H),Khezu (H)",
    "omniplegia sac":        "Volvidon (H)",
    "pale bone":             "Khezu (L/H)",
    "pale extract":          "Khezu (L/H)",
    "pale steak":            "Khezu (H)",
    "paralysis sac":         "Volvidon (L)",
    "pearl hide":            "Khezu (H)",
    "poison sac":            "Great Wroggi (L)",
    "rich mud":              "Barroth (H)",
    "royal ludroth scale":   "Royal Ludroth (L)",
    "royal ludroth scale+":   "Royal Ludroth (H)",
    "royal ludroth claw":    "Royal Ludroth (L)",
    "royal ludroth claw+":    "Royal Ludroth (H)",
    "royal ludroth crest":   "Royal Ludroth (L)",
    "royal ludroth crest+":   "Royal Ludroth (H)",
    "royal ludroth tail":    "Royal Ludroth (L/H)",
    "screamer sac":          "Great Izuchi (L/H)",
    "sleep sac":             "Great Baggi (L)",
    "spongy hide":           "Royal Ludroth (L)",
    "spongy hide+":          "Royal Ludroth (H)",
    "stoutbone":             "Arzuros (H),Lagombi (H),Volvidon (H)",
    "suspicious fang":       "Khezu (L)",
    "suspicious fang+":      "Khezu (H)",
    "timeworn crimson horn": "Daimyo Hermitaur (M)",
    "thunder sac":           "Khezu (H)",
    "torrent sac":           "Royal Ludroth (H)",
    "toxin sac":             "Great Wroggi (H)",
    "volvidon shell":        "Volvidon (L)",
    "volvidon carapace":     "Volvidon (H)",
    "volvidon claw":         "Volvidon (L)",
    "vovlidon claw+":        "Volvidon (H)",
    "volvidon rickrack":     "Volvidon (L/H)",
    "wyvern gem":            "All High Rank or Master Rank Wyverns/Leviathans",
    "wyvern tear":           "All Low Rank High Rank or Master Rank Wyverns/Leviathans}"
}